micronaut:
  server:
    port: 8091

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_DEFAULT_REGION}
  sqs:
    queues:
      card-application:
        queue-url: ${AWS_SQS_CARD_APPLICATION_QUEUE_URL}

  sns:
    topics:
      bank-account-created:
        topic-arn: ${AWS_SNS_BANK_ACCOUNT_CREATED_TOPIC_ARN}