micronaut:
  server:
    port: 8091
  serialization:
    enabled: true

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_DEFAULT_REGION}
  sqs:
    queues:
      card-application:
        queue-url: ${AWS_SQS_CARD_APPLICATION_QUEUE_URL}

  sns:
    topics:
      account-holder-created:
        topic-arn: ${AWS_SNS_ACCOUNT_HOLDER_CREATED_TOPIC_ARN}