aws:
  access-key-id: 'test'
  secret-key: 'test'
  region: 'us-east-1'
  dynamodb:
    endpoint: 'http://localhost:4566'
    tables:
      banking-entities:
        table-name: 'banking-entities-localstack'
  sns:
    topics:
      bank-account-created:
        topic-name: 'bank-account-created-localstack'